[package]
name = "unknown"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glob = "0.3.0"
knuffel = "2.0"
miette = { version="4.3.0", features=["fancy"] }
petgraph = "0.6"

[dev-dependencies]
insta = "1.19"