name: build

on:
  push:
  pull_request:
    branches: [master]

env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: "-D warnings"
  RUST_BACKTRACE: short
  NEXTEST_PROFILE: ci
  CI: 1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v1
      - uses: dtolnay/rust-toolchain@1.66.0
        with:
          components: rustfmt

      - name: Check formatting
        shell: bash
        run: cargo fmt --all --check

      - name: Build crux
        shell: bash
        run: cargo build --workspace

      - name: Install nextest
        shell: bash
        run: |
          curl -LsSf https://get.nexte.st/0.9/linux | tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin

      - name: Build tests
        shell: bash
        run: |
          cargo nextest run --workspace --all-features --no-run

      - name: Run tests
        shell: bash
        run: |
          cargo nextest run --workspace --all-features

      - name: Build & run doctests
        shell: bash
        run: |
          cargo test --doc --workspace

